kind: ServiceAccount
apiVersion: v1
metadata:
  name: kube-applier
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /__/metrics
    prometheus.io/port: "8080"
  name: kube-applier
  labels:
    app: kube-applier
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: kube-applier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-applier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-applier
  template:
    metadata:
      labels:
        app: kube-applier
    spec:
      serviceAccountName: kube-applier
      containers:
        - name: kube-applier
          image: quay.io/utilitywarehouse/kube-applier:2.5.4
          env:
            - name: NAMESPACES_DIR
              value: "base"
            - name: REPO_PATH
              value: "/src/manifests/$(NAMESPACES_DIR)"
            - name: DIFF_URL_FORMAT
              value: "https://github.com/org/repo/commit/%s"
            - name: LOG_LEVEL
              value: warn
          volumeMounts:
            - name: git-repo
              mountPath: /src
              readOnly: true
          resources:
            requests:
              cpu: 10m
              memory: 25Mi
            limits:
              cpu: 500m
              memory: 400Mi
          ports:
            - containerPort: 8080
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.1.7
          securityContext:
            runAsUser: 65533 # git-sync user
            runAsGroup: 0 # root group to read mounted Secrets
          env:
            - name: GIT_SYNC_REPO
              value: "git@github.com:org/repo.git"
            - name: GIT_SYNC_DEST
              value: "manifests"
            - name: GIT_SYNC_SSH
              value: "true"
            - name: GIT_SYNC_MAX_SYNC_FAILURES
              value: "5"
          volumeMounts:
            - name: git-repo
              mountPath: /tmp/git
            - name: git-secret
              mountPath: /etc/git-secret
          resources:
            requests:
              cpu: 40m
              memory: 48Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: git-repo
          emptyDir: {}
        - name: git-secret
          secret:
            secretName: ssh
            defaultMode: 0440
