
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kube-applier
rules:
- apiGroups:
  - kube-applier.io
  resources:
  - waybills
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube-applier.io
  resources:
  - waybills/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kube-applier.io
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube-applier.io
  resources:
  - repositories/status
  verbs:
  - get
  - patch
  - update
