kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-applier
rules:
  - apiGroups: ["kube-applier.io"]
    resources: ["waybills"]
    verbs: ["list"]
  - apiGroups: ["kube-applier.io"]
    resources: ["waybills/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
