kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-applier
rules:
  - apiGroups: ["kube-applier.io"]
    resources: ["waybills"]
    verbs: ["list", "watch"]
  - apiGroups: ["kube-applier.io"]
    resources: ["waybills/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - kube-applier-delegate-token
      - kube-applier-git-ssh
      - kube-applier-strongbox-keyring
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
