kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-applier-admin
subjects:
  - kind: ServiceAccount
    name: kube-applier-assumed
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kube-applier-assumed
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-applier
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts", "secrets"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: assume-kube-applier
subjects: []
roleRef:
  kind: Role
  name: kube-applier
  apiGroup: rbac.authorization.k8s.io