apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-applier
spec:
  template:
    spec:
      containers:
      - name: kube-applier
        env:
        - name: NAMESPACES_DIR
          value: "example-env"
        - name: DIFF_URL_FORMAT
          value: "https://github.com/org/repo/commit/%s"
      - name: git-sync
        env:
        - name: GIT_SYNC_REPO
          value: "git@github.com:org/repo.git"
