apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-applier
spec:
  template:
    spec:
      containers:
      - name: kube-applier
        env:
        - name: DIFF_URL_FORMAT
          value: "https://github.com/org/repo/commit/%s"
        - name: REPO_PATH
          value: "example-env"
        - name: REPO_REMOTE
          value: "git@github.com:org/repo.git"
