apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-applier
  labels:
    kubernetes.io/ingress.class: private-example
  annotations:
    external-dns.alpha.kubernetes.io/target: example.com
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: kube-applier
            port: 80
