apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base/
resources:
# **important** these rbac resources need to exist in each namespace managed by
# kube-applier
- kube-applier-ingress.yaml
- rbac.yaml
patchesStrategicMerge:
- kube-applier-patch.yaml
secretGenerator:
- name: ssh
  type: Opaque
  files:
  - ssh=secrets/ssh
  - known_hosts=secrets/known_hosts
- name: strongbox
  files:
  - .strongbox_keyring=secrets/strongbox_keyring
