# Used by kube-applier to apply resources in this namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-applier-delegate
---
# Creates a secret with fixed name, populated with the kube-applier-delegate SA
# data by the token controller.
# https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: kube-applier-delegate-token
  annotations:
    kubernetes.io/service-account.name: kube-applier-delegate
---
# The kube-applier-delegate SA should be an admin in this namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-applier-delegate
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: kube-applier-delegate
